Add network (live/testnet) switcher to transfer widget
edgeware-network/Edgeware-Website pull request #70
Opened 2023-05-19 16:39 UTC by johny

2023-05-30 22:20 UTC, ShankarWarang submitted a review, later dismissed

2023-05-30 22:25 UTC, ShankarWarang commented
Is it possible to add auto network switching when user clicks on the mainnet/testnet or when connects EVM wallet? And if the EdgeEVM/BereEVM is not configured, will it prompt the EVM wallet (metamask) to add the corresponding network?

2023-06-23 19:16 UTC, johny commented
@ShankarWarang - the logic should be fixed now ;-)

2023-06-26 11:43 UTC, ShankarWarang approved these changes

2023-06-26 11:46 UTC, ShankarWarang commented
I'm getting 'Insufficient balance' error now while depositing from EdgeWASM to EdgeEVM. @johny

2023-06-29 22:58 UTC, johny commented
> I'm getting 'Insufficient balance' error now while depositing from EdgeWASM to EdgeEVM. @johny

Try again! I've fixed some issues related to that.

2023-06-30 18:52 UTC, ShankarWarang requested changes
Requesting the minor change for lib/crypto/withdrawal.ts : L64

2023-06-30 18:52 UTC, ShankarWarang commented on lib/crypto/withdrawal.ts
> +  const difference = Math.floor(actualAmount - BUFFER - amount);
No need to deduct 'BUFFER'.

2023-07-03 18:23 UTC, johny commented
> Requesting the minor change for lib/crypto/withdrawal.ts : L64

Adressed in [2eaf08b](https://github.com/edgeware-network/Edgeware-Website/pull/70/commits/2eaf08b523922facd9d8058ab5c99e1ba74a36a6)

2023-07-03 20:00 UTC, ShankarWarang approved these changes

2023-07-04 08:19 UTC, merged